
#Contains configs only accessed by the server
[Server]
	#These potion effects will be applied to the player upon being saved from death by a non-held bound totem of undying. Each string specifies a potion effect in exactly the same way the /effect command does (e.i. the required first argument specifies a potion by id or by modId:name, and the second/third optional arguments are duration in seconds and amplification). These effects will be applied whether or not pre-existing effects were previously cleared.
	"Apply Potion Effects" = ["minecraft:regeneration 45 1", "minecraft:absorption 5 1"]
	#If set to true, the large floating totem animation will that takes up the screen will play upon upon being saved from death by a non-held bound totem of undying.
	"Play Animation" = false
	#If set to true, totem particles will spawn for all nearby players upon being saved from death by a non-held bound totem of undying.
	"Spawn Particles" = true
	#If set to true, totem sound will play for all nearby players upon being saved from death by a non-held bound totem of undying.
	"Play Sound" = true
	#Specifies the time in seconds between syncing of the client's bound shelf positions to the server while holding a bound compass.
	#Range: 0.05 ~ 1.7976931348623157E308
	"Bound Compass Sync Interval" = 5.0
	#If set to true, 'New Health Value' will specify the percent of the player's max heath to set the new health value to upon being saved from death by a non-held bound totem of undying. If set to false, it will specify the number of hearts (1 = 1/2 heart) to set the new health value to.
	"Set Health To Percentage Of Max" = false
	#Specifies the maximum number of shelves that can be bound to an entity at a time. If an additional shelf is bound once the max has been reached, a randomly selected currently bound shelf will be struck with lightning and converted into a useless charred shelf. Items can be taken from a charred shelf but cannot be placed in it, and any totems it will have no effect as long as they remain in it.
	#Range: > 1
	"Max Bound Shelves" = 10
	#1) If set to WHOLE_INVENTORY, the entire inventory will be searched for totems; 2) If set to HOTBAR_ONLY, only the hotbar of the inventory will be searched for totems; 3) If set to HELD_ONLY, only totems that the player is holding will save them from death.
	#Allowed Values: WHOLE_INVENTORY, HOTBAR_ONLY, HELD_ONLY
	"Inventory Search Location" = "WHOLE_INVENTORY"
	#If set to true, non-held bound totems of undying can save the player from death even from damage sources that harm players in creative mode (such as void damage and /kill command damage).
	"Prevent All Death" = true
	#Specifies the value (either percentage of max health, or absolute value (1 = 1/2 heart), depending on what 'Set Health To Percentage Of Max' is set to) that the players heath will be set to upon being saved from death by a non-held bound totem of undying.
	#Range: 0.0 ~ 1.7976931348623157E308
	"New Health Value" = 1.0
	#If set to true, all pre-existing potion effects will be cleared from the player upon being saved from death by a non-held bound totem of undying.
	"Clear Potion Effects" = true
	#Specifies the maximum distance in meters from a totem shelf an entity must be when binding that shelf to that entity for the binding to be successful.
	#Range: 0.0 ~ 1.7976931348623157E308
	"Max Distance To Shelf" = 10.0

