
#Server configuration settings
[server]
	#Every this many game ticks, the mod will check wether the currently tracked concrete powder items are in water, and if they are, will convert them. The default is 20 ticks, or 1 second.
	#Range: 1 ~ 200
	conversionCheckDelay = 20
	#If true, only items thrown by the player will be converted into concrete.If false, all concrete powder items will be converted, including items dispensed by droppers, items that drop when a chest is destroyed, etc.
	onlyPlayerThrownItems = true
	#After this many game ticks spent in water, the item will be converted.
	#Range: 0 ~ 6000
	conversionDelay = 0

