
["Regrowth Control Values"]
	#Eating Heals: 0-No, 1-yes
	#Range: 0.0 ~ 1.0
	eatingHeals = 0.99
	#Debug Level: 0 = Off, 1 = Log, 2 = Chat+Log
	#Range: 0 ~ 2
	debugLevel = 0

["Regrowth Mobs 6464"]
	#RegrowthMobs String 6464
	defaultRegrowthMobsActual = "minecraft:cow,both,240.0;minecraft:horse,eat,360.0;minecraft:donkey,eat,360.0;minecraft:sheep,eat,240.0;minecraft:pig,grow,800.0;minecraft:bee,grow,1000.0;minecraft:chicken,grow,600.0;minecraft:villager,crwlvpt,5.0;minecraft:creeper,tall,60.0"

