#Restock
Restock = true
#Use fixed items
UseFixedItems = false
#Fixed items
FixedItems = "minecraft:air;minecraft:air;minecraft:air;minecraft:air;minecraft:air;minecraft:air;minecraft:air"
#Include Mods
IncludeMods = "*"
#Exclude Mods
ExcludeMods = "draconicevolution;avaritia"
#Exclude Items
ExcludeItems = "minecraft:nether_star;minecraft:beacon;minecraft:shulker_box;minecraft:colorset*shulker_box;minecraft:elytra;minecraft:end_portal_frame;vm:vending_machine"
#Include Creative Tab Groups
IncludeGroups = "*"
#Exclude Creative Tab Groups
ExcludeGroups = "!"
#Change item rarity value for pricing
ItemRarity = "minecraft:emerald_block=1;minecraft:diamond_block=1;minecraft:armorset*diamond=1;minecraft:toolset*diamond=1"

[RarityData]
	#Uncommon Item
	UncommonItem = "minecraft:emerald"
	#Rare Item
	RareItem = "minecraft:emerald"
	#Uncommon Cost
	#Range: 1 ~ 64
	UncommonCost = 16
	#Rare Uses
	#Range: 1 ~ 32
	RareUses = 2
	#Epic Uses
	#Range: 1 ~ 32
	EpicUses = 1
	#Epic Item
	EpicItem = "minecraft:emerald"
	#Common Item
	CommonItem = "minecraft:emerald"
	#Epic Cost
	#Range: 1 ~ 64
	EpicCost = 64
	#Rare Cost
	#Range: 1 ~ 64
	RareCost = 32
	#Common Uses
	#Range: 1 ~ 32
	CommonUses = 8
	#Uncommon Uses
	#Range: 1 ~ 32
	UncommonUses = 4
	#Common Cost
	#Range: 1 ~ 64
	CommonCost = 1

