
["Balance Options"]
	#Minimum temperature of fluid at which the Ceramic Bucket breaks when emptied. (-1 means that bucket never breaks caused by high fluid temperature)
	#Range: -1 ~ 10000
	ceramicBucketBreakTemperature = 1000

