
#Options for the Nether Update
[nether_update]
	#Whether the Warped Forest biome is added
	warped_forest = false
	#Whether the Locate biome command is added
	locate_biome_command = true
	#Whether the Crimson Forest biome is added
	soul_sand_valley = false
	#Whether the smithing table has functionality
	smithing_table = true
	#Whether netherite and netherite equipment is added
	netherite = true

	#Options for the Nether Update
	[nether_update.ancient_debris]
		#Whether ancient debris is added
		ancient_debris = true
		#Whether ancient debris generates in the nether
		ancient_debris_generates = true

