
[wellfedconfig]
	#Range: 0 ~ 48000
	stick_of_meat_buff_duration = 12000
	#Range: 0 ~ 100
	squid_limb_drop_chance = 50
	#Range: 0 ~ 100
	rare_book_drop_chance = 2
	#Range: 0 ~ 48000
	firecracker_salmon_buff_duration = 3000
	#Range: 0 ~ 48000
	first_night_meal_buff_duration = 6000
	#WellFed Config | Duration inputs ranges from: 0 - 48000 and drop rates: 0 - 100 %
	#Range: 0 ~ 48000
	great_feast_buff_duration = 12000
	#Range: 0 ~ 48000
	seafood_magnifique_buff_duration = 6000
	#Range: 0 ~ 100
	bat_wing_drop_chance = 50
	#Range: 0 ~ 48000
	steves_mining_meal_buff_duration = 24000

